check-eyes/config/routes.rb
Rails.application.routes.draw do
  resources :boards
  get "/in" => "boards#in"
  get "/landing" => "boards#landing"
  get "/check" => "boards#check"
  get "/result" => "boards#result"

end

check-eyes/app/models/board.rb
class Board < ActiveRecord::Base
end

check-eyes/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

check-eyes/app/controllers/boards_controller.rb
require 'socket'

class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]

  # GET /boards
  # GET /boards.json
  def index
    @boards = Board.all
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards
  # POST /boards.json
  def create
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url, notice: 'Board was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def in
    puts "@@distance: #{@@distance}"
    puts "params[:a]: #{params[:a]}"
    if @@flag == 0
      @@distance = params[:a]
    end
    render nothing: true
  end

  def landing
    @@distance = 0
    @@count = 0
    @@sight = 0.5
    @@flag = 0
  end

  def check
    @@flag = 1
    puts "@@distance: #{@@distance}"
    puts "params[:input] #{params[:input]}"

    #@distance = @@distance
    if params[:input] == "1"
      @@sight = @@sight + 0.1
    else
      @@sight = @@sight - 0.1
    end

    @distance = 50
    @sight = @@sight
    @@count = @@count + 1
    
    if (@@count == 11)
      redirect_to :result
    end

    @count = @@count
    @num = Random.new.rand(1..9)
  end

  def result
    @sight = @@sight
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params[:board]
    end
end

check-eyes/app/helpers/application_helper.rb
module ApplicationHelper
end

check-eyes/app/helpers/boards_helper.rb
module BoardsHelper
end

check-eyes/app/views/boards/_form.html.erb
<%= form_for(@board) do |f| %>
  <% if @board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
      <% @board.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

check-eyes/app/views/boards/check.html.erb
<%= stylesheet_link_tag    'boards', media: 'all', 'data-turbolinks-track' => true %>
<meta name="viewport" content="width=device-width, user-scalable=no">
sight <%= @sight %><br/>
count <%= @count %>
<div id="numContainer"><div id="num"><%= @num %></div></div>
<div id="inputContainer">
	<div id="inputs">
		<ul>
			<li class="inputNum"><input type="hidden" value="1" /><img src="/assets/1.png" /></li>
			<li class="inputNum"><input type="hidden" value="2" /><img src="/assets/2.png" /></li>
			<li class="inputNum"><input type="hidden" value="3" /><img src="/assets/3.png" /></li>
			<li class="inputNum"><input type="hidden" value="4" /><img src="/assets/4.png" /></li>
			<li class="inputNum"><input type="hidden" value="5" /><img src="/assets/5.png" /></li>
			<li class="inputNum"><input type="hidden" value="6" /><img src="/assets/6.png" /></li>
			<li class="inputNum"><input type="hidden" value="7" /><img src="/assets/7.png" /></li>
			<li class="inputNum"><input type="hidden" value="8" /><img src="/assets/8.png" /></li>
			<li class="inputNum"><input type="hidden" value="9" /><img src="/assets/9.png" /></li>
		</ul>
		<form id="target" action="/check">
			<input id="formInput" type="hidden" name="input" />
		</form>
	</div>
</div>
<script>
	$('#num').css('font-size', <%= @distance %>/(<%= @sight %> * 5));

	$('.inputNum').click(function() {
		var input = $(this.childNodes[0]).attr('value');
		// $('#target').innerHTML = input;
		if ($('#num').text() == input) {
			$('#formInput').val("1");	
		}

		$('#target').submit();
	});
</script>

check-eyes/app/views/boards/edit.html.erb
<h1>Editing board</h1>

<%= render 'form' %>

<%= link_to 'Show', @board %> |
<%= link_to 'Back', boards_path %>

check-eyes/app/views/boards/index.html.erb
<h1>Listing boards</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @boards.each do |board| %>
      <tr>
        <td><%= link_to 'Show', board %></td>
        <td><%= link_to 'Edit', edit_board_path(board) %></td>
        <td><%= link_to 'Destroy', board, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Board', new_board_path %>

check-eyes/app/views/boards/landing.html.erb
<div>
	<div style="width: 300px; height:500px; margin: 0 auto">
		<img src="assets/glasses.png" style="width: 100%; height:100%;"/>
	</div>
	<div style="width:100px; height:50px; margin: 0 auto;">
		<a href="/check">
		<img src="/assets/start.png" style="width: 100%; height: 100%;"/></a>
	</div>
</div>

check-eyes/app/views/boards/new.html.erb
<h1>New board</h1>

<%= render 'form' %>

<%= link_to 'Back', boards_path %>

check-eyes/app/views/boards/result.html.erb
<%= stylesheet_link_tag    'boards', media: 'all', 'data-turbolinks-track' => true %>
<div id="result">시력: <%= @sight %></div>

check-eyes/app/views/boards/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_board_path(@board) %> |
<%= link_to 'Back', boards_path %>

check-eyes/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CheckEyes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>